stages:
  - build

group15:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build

  before_script:
    - echo $CI_PROJECT_DIR

  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile ./Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

  only:
    - master

  tags:
    - daedalus

